# Generated by Django 3.2 on 2021-04-10 20:12

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32),
                                                                   size=None)),
                ('doing', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32),
                                                                    size=None)),
                ('review', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32),
                                                                     size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255)),
                ('type', models.IntegerField(choices=[(1, 'Github'), (2, 'Gitlab'), (3, 'Jira')])),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_service_username', models.CharField(max_length=255)),
                ('token', models.CharField(max_length=255)),
                ('map', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='aggregator.map')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aggregator.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
