name: Lint

on: [push]

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    name: Flake8 Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: flake8 Lint
        uses: py-actions/flake8@v1
        with:
          path: "task_aggregator"
          max-line-length: "120"
  eslint:
    runs-on: ubuntu-latest
    name: ESLint
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: npm ci
      working-directory: task_aggregator
    - run: npx eslint . --ext .js
      working-directory: task_aggregator
